apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-acajas
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/jenkins
  storageClassName: jenkins