rbac:
  useOpenShiftNonRootSCC: true
controller:
  numExecutors: 7
  route:
    enabled: true

# persistence:
#   enabled: true
#   existingClaim: jenkins-pvc
#   storageClass: "jenkins"
#   size: 20Gi